services:
  n8n_clipper:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_clipper
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./n8n_data:/home/node/.n8n
      # Kita HANYA me-mount folder skrip untuk simpan output jika diperlukan nanti
      - ./scripts:/home/node/scripts

  discord-bridge:
    image: node:20-alpine
    container_name: discord_bridge
    restart: always
    env_file:
      - .env
    volumes:
      - ./scripts:/app
    working_dir: /app
    command: sh -c "npm install discord.js axios && node discord-bridge.js"